DROP DATABASE IF EXISTS dojo;
CREATE DATABASE dojo;
USE dojo;

DROP TABLE IF EXISTS dojo.NINJA;

CREATE TABLE dojo.NINJA  (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CLAN VARCHAR(50),
    CONSTRAINT ninja_type_pk PRIMARY KEY (ID, TYPE)
);

INSERT INTO dojo.CLAN VALUES (0, 'TSUSHIMA');
INSERT INTO dojo.CLNA VALUES (1, 'YAKUZA');